# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class JsonAttributoValue(BaseModel):
    """
    JsonAttributoValue
    """ # noqa: E501
    attributo_id: StrictInt
    attributo_value_str: Optional[StrictStr] = None
    attributo_value_int: Optional[StrictInt] = None
    attributo_value_chemical: Optional[StrictInt] = None
    attributo_value_datetime: Optional[StrictInt] = None
    attributo_value_float: Optional[Union[StrictFloat, StrictInt]] = None
    attributo_value_bool: Optional[StrictBool] = None
    attributo_value_list_str: Optional[List[StrictStr]] = None
    attributo_value_list_float: Optional[List[Union[StrictFloat, StrictInt]]] = None
    attributo_value_list_bool: Optional[List[StrictBool]] = None
    __properties: ClassVar[List[str]] = ["attributo_id", "attributo_value_str", "attributo_value_int", "attributo_value_chemical", "attributo_value_datetime", "attributo_value_float", "attributo_value_bool", "attributo_value_list_str", "attributo_value_list_float", "attributo_value_list_bool"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JsonAttributoValue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JsonAttributoValue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attributo_id": obj.get("attributo_id"),
            "attributo_value_str": obj.get("attributo_value_str"),
            "attributo_value_int": obj.get("attributo_value_int"),
            "attributo_value_chemical": obj.get("attributo_value_chemical"),
            "attributo_value_datetime": obj.get("attributo_value_datetime"),
            "attributo_value_float": obj.get("attributo_value_float"),
            "attributo_value_bool": obj.get("attributo_value_bool"),
            "attributo_value_list_str": obj.get("attributo_value_list_str"),
            "attributo_value_list_float": obj.get("attributo_value_list_float"),
            "attributo_value_list_bool": obj.get("attributo_value_list_bool")
        })
        return _obj


