# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List
from amarcord_open.models.json_merge_parameters import JsonMergeParameters
from typing import Optional, Set
from typing_extensions import Self

class JsonQueueMergeJobInput(BaseModel):
    """
    JsonQueueMergeJobInput
    """ # noqa: E501
    strict_mode: StrictBool
    indexing_parameters_id: StrictInt
    data_set_id: StrictInt
    merge_parameters: JsonMergeParameters
    __properties: ClassVar[List[str]] = ["strict_mode", "indexing_parameters_id", "data_set_id", "merge_parameters"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JsonQueueMergeJobInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of merge_parameters
        if self.merge_parameters:
            _dict['merge_parameters'] = self.merge_parameters.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JsonQueueMergeJobInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "strict_mode": obj.get("strict_mode"),
            "indexing_parameters_id": obj.get("indexing_parameters_id"),
            "data_set_id": obj.get("data_set_id"),
            "merge_parameters": JsonMergeParameters.from_dict(obj["merge_parameters"]) if obj.get("merge_parameters") is not None else None
        })
        return _obj


