# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.associated_table import AssociatedTable

class TestAssociatedTable(unittest.TestCase):
    """AssociatedTable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssociatedTable(self):
        """Test AssociatedTable"""
        # inst = AssociatedTable()

if __name__ == '__main__':
    unittest.main()
