# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amarcord_open.api.experimenttypes_api import ExperimenttypesApi


class TestExperimenttypesApi(unittest.IsolatedAsyncioTestCase):
    """ExperimenttypesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ExperimenttypesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_change_current_run_experiment_type_api_experiment_types_change_for_run_post(self) -> None:
        """Test case for change_current_run_experiment_type_api_experiment_types_change_for_run_post

        Change Current Run Experiment Type
        """
        pass

    async def test_copy_experiment_types_api_copy_experiment_types_post(self) -> None:
        """Test case for copy_experiment_types_api_copy_experiment_types_post

        Copy Experiment Types
        """
        pass

    async def test_create_experiment_type_api_experiment_types_post(self) -> None:
        """Test case for create_experiment_type_api_experiment_types_post

        Create Experiment Type
        """
        pass

    async def test_delete_experiment_type_api_experiment_types_delete(self) -> None:
        """Test case for delete_experiment_type_api_experiment_types_delete

        Delete Experiment Type
        """
        pass

    async def test_read_experiment_types_api_experiment_types_beamtime_id_get(self) -> None:
        """Test case for read_experiment_types_api_experiment_types_beamtime_id_get

        Read Experiment Types
        """
        pass


if __name__ == '__main__':
    unittest.main()
