# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amarcord_open.models.chemical_type import ChemicalType

class TestChemicalType(unittest.TestCase):
    """ChemicalType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChemicalType(self):
        """Test ChemicalType"""
        # inst = ChemicalType()

if __name__ == '__main__':
    unittest.main()
