# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.json_create_attributo_output import JsonCreateAttributoOutput

class TestJsonCreateAttributoOutput(unittest.TestCase):
    """JsonCreateAttributoOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JsonCreateAttributoOutput:
        """Test JsonCreateAttributoOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JsonCreateAttributoOutput`
        """
        model = JsonCreateAttributoOutput()
        if include_optional:
            return JsonCreateAttributoOutput(
                id = 56
            )
        else:
            return JsonCreateAttributoOutput(
                id = 56,
        )
        """

    def testJsonCreateAttributoOutput(self):
        """Test JsonCreateAttributoOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
