# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amarcord_open.models.json_merge_status import JsonMergeStatus

class TestJsonMergeStatus(unittest.TestCase):
    """JsonMergeStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJsonMergeStatus(self):
        """Test JsonMergeStatus"""
        # inst = JsonMergeStatus()

if __name__ == '__main__':
    unittest.main()
