# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amarcord_open.api.analysis_api import AnalysisApi


class TestAnalysisApi(unittest.IsolatedAsyncioTestCase):
    """AnalysisApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AnalysisApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_read_analysis_results_api_analysis_analysis_results_post(self) -> None:
        """Test case for read_analysis_results_api_analysis_analysis_results_post

        Read Analysis Results
        """
        pass

    async def test_read_beamtime_geometry_details_api_run_analysis_beamtime_id_geometry_get(self) -> None:
        """Test case for read_beamtime_geometry_details_api_run_analysis_beamtime_id_geometry_get

        Read Beamtime Geometry Details
        """
        pass

    async def test_read_run_analysis_api_run_analysis_beamtime_id_get(self) -> None:
        """Test case for read_run_analysis_api_run_analysis_beamtime_id_get

        Read Run Analysis
        """
        pass

    async def test_read_single_data_set_results_api_analysis_single_data_set_beamtime_id_data_set_id_get(self) -> None:
        """Test case for read_single_data_set_results_api_analysis_single_data_set_beamtime_id_data_set_id_get

        Read Single Data Set Results
        """
        pass

    async def test_read_single_merge_result_api_analysis_merge_result_beamtime_id_experiment_type_id_merge_result_id_get(self) -> None:
        """Test case for read_single_merge_result_api_analysis_merge_result_beamtime_id_experiment_type_id_merge_result_id_get

        Read Single Merge Result
        """
        pass


if __name__ == '__main__':
    unittest.main()
