# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.json_live_stream import JsonLiveStream

class TestJsonLiveStream(unittest.TestCase):
    """JsonLiveStream unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JsonLiveStream:
        """Test JsonLiveStream
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JsonLiveStream`
        """
        model = JsonLiveStream()
        if include_optional:
            return JsonLiveStream(
                file_id = 56,
                modified = 56
            )
        else:
            return JsonLiveStream(
                file_id = 56,
                modified = 56,
        )
        """

    def testJsonLiveStream(self):
        """Test JsonLiveStream"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
