# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amarcord_open.models.json_merge_parameters import JsonMergeParameters

class TestJsonMergeParameters(unittest.TestCase):
    """JsonMergeParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JsonMergeParameters:
        """Test JsonMergeParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JsonMergeParameters`
        """
        model = JsonMergeParameters()
        if include_optional:
            return JsonMergeParameters(
                point_group = '',
                space_group = '',
                cell_description = '',
                negative_handling = 'ignore',
                merge_model = 'unity',
                scale_intensities = 'off',
                post_refinement = True,
                iterations = 56,
                polarisation = amarcord_open.models.json_polarisation.JsonPolarisation(
                    angle = 56, 
                    percent = 56, ),
                start_after = 56,
                stop_after = 56,
                rel_b = 1.337,
                no_pr = True,
                force_bandwidth = 1.337,
                force_radius = 1.337,
                force_lambda = 1.337,
                no_delta_cc_half = True,
                max_adu = 1.337,
                min_measurements = 56,
                logs = True,
                min_res = 1.337,
                push_res = 1.337,
                w = '',
                ambigator_command_line = ''
            )
        else:
            return JsonMergeParameters(
                point_group = '',
                cell_description = '',
                merge_model = 'unity',
                scale_intensities = 'off',
                post_refinement = True,
                iterations = 56,
                rel_b = 1.337,
                no_pr = True,
                no_delta_cc_half = True,
                min_measurements = 56,
                logs = True,
                ambigator_command_line = '',
        )
        """

    def testJsonMergeParameters(self):
        """Test JsonMergeParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
