# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amarcord_open.models.json_read_indexing_parameters_output import JsonReadIndexingParametersOutput

class TestJsonReadIndexingParametersOutput(unittest.TestCase):
    """JsonReadIndexingParametersOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JsonReadIndexingParametersOutput:
        """Test JsonReadIndexingParametersOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JsonReadIndexingParametersOutput`
        """
        model = JsonReadIndexingParametersOutput()
        if include_optional:
            return JsonReadIndexingParametersOutput(
                data_set_id = 56,
                cell_description = '',
                sources = [
                    ''
                    ]
            )
        else:
            return JsonReadIndexingParametersOutput(
                data_set_id = 56,
                cell_description = '',
                sources = [
                    ''
                    ],
        )
        """

    def testJsonReadIndexingParametersOutput(self):
        """Test JsonReadIndexingParametersOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
