# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amarcord_open.models.json_beamtime_schedule import JsonBeamtimeSchedule

class TestJsonBeamtimeSchedule(unittest.TestCase):
    """JsonBeamtimeSchedule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JsonBeamtimeSchedule:
        """Test JsonBeamtimeSchedule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JsonBeamtimeSchedule`
        """
        model = JsonBeamtimeSchedule()
        if include_optional:
            return JsonBeamtimeSchedule(
                schedule = [
                    amarcord_open.models.json_beamtime_schedule_row.JsonBeamtimeScheduleRow(
                        users = '', 
                        date = '', 
                        shift = '', 
                        comment = '', 
                        td_support = '', 
                        chemicals = [
                            56
                            ], 
                        start_posix = 56, 
                        stop_posix = 56, )
                    ]
            )
        else:
            return JsonBeamtimeSchedule(
                schedule = [
                    amarcord_open.models.json_beamtime_schedule_row.JsonBeamtimeScheduleRow(
                        users = '', 
                        date = '', 
                        shift = '', 
                        comment = '', 
                        td_support = '', 
                        chemicals = [
                            56
                            ], 
                        start_posix = 56, 
                        stop_posix = 56, )
                    ],
        )
        """

    def testJsonBeamtimeSchedule(self):
        """Test JsonBeamtimeSchedule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
