# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.json_read_beamtime import JsonReadBeamtime

class TestJsonReadBeamtime(unittest.TestCase):
    """JsonReadBeamtime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JsonReadBeamtime:
        """Test JsonReadBeamtime
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JsonReadBeamtime`
        """
        model = JsonReadBeamtime()
        if include_optional:
            return JsonReadBeamtime(
                beamtimes = [
                    openapi_client.models.json_beamtime.JsonBeamtime(
                        id = 56, 
                        external_id = '', 
                        proposal = '', 
                        beamline = '', 
                        title = '', 
                        comment = '', 
                        start = 56, 
                        end = 56, 
                        chemical_names = [
                            ''
                            ], 
                        analysis_output_path = '', )
                    ]
            )
        else:
            return JsonReadBeamtime(
                beamtimes = [
                    openapi_client.models.json_beamtime.JsonBeamtime(
                        id = 56, 
                        external_id = '', 
                        proposal = '', 
                        beamline = '', 
                        title = '', 
                        comment = '', 
                        start = 56, 
                        end = 56, 
                        chemical_names = [
                            ''
                            ], 
                        analysis_output_path = '', )
                    ],
        )
        """

    def testJsonReadBeamtime(self):
        """Test JsonReadBeamtime"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
