# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.config_api import ConfigApi


class TestConfigApi(unittest.IsolatedAsyncioTestCase):
    """ConfigApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ConfigApi()

    async def asyncTearDown(self) -> None:
        pass

    async def test_read_indexing_parameters_api_user_config_beamtime_id_online_indexing_parameters_get(self) -> None:
        """Test case for read_indexing_parameters_api_user_config_beamtime_id_online_indexing_parameters_get

        Read Indexing Parameters
        """
        pass

    async def test_read_user_configuration_single_api_user_config_beamtime_id_key_get(self) -> None:
        """Test case for read_user_configuration_single_api_user_config_beamtime_id_key_get

        Read User Configuration Single
        """
        pass

    async def test_update_online_indexing_parameters_api_user_config_beamtime_id_online_indexing_parameters_patch(self) -> None:
        """Test case for update_online_indexing_parameters_api_user_config_beamtime_id_online_indexing_parameters_patch

        Update Online Indexing Parameters
        """
        pass

    async def test_update_user_configuration_single_api_user_config_beamtime_id_key_value_patch(self) -> None:
        """Test case for update_user_configuration_single_api_user_config_beamtime_id_key_value_patch

        Update User Configuration Single
        """
        pass


if __name__ == '__main__':
    unittest.main()
