# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amarcord_open.models.json_user_config import JsonUserConfig

class TestJsonUserConfig(unittest.TestCase):
    """JsonUserConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JsonUserConfig:
        """Test JsonUserConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JsonUserConfig`
        """
        model = JsonUserConfig()
        if include_optional:
            return JsonUserConfig(
                online_crystfel = True,
                auto_pilot = True,
                current_experiment_type_id = 56,
                current_online_indexing_parameters_id = 56
            )
        else:
            return JsonUserConfig(
                online_crystfel = True,
                auto_pilot = True,
        )
        """

    def testJsonUserConfig(self):
        """Test JsonUserConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
