# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.json_indexing_fom import JsonIndexingFom

class TestJsonIndexingFom(unittest.TestCase):
    """JsonIndexingFom unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JsonIndexingFom:
        """Test JsonIndexingFom
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JsonIndexingFom`
        """
        model = JsonIndexingFom()
        if include_optional:
            return JsonIndexingFom(
                hit_rate = 1.337,
                indexing_rate = 1.337,
                indexed_frames = 56,
                detector_shift_x_mm = 1.337,
                detector_shift_y_mm = 1.337
            )
        else:
            return JsonIndexingFom(
                hit_rate = 1.337,
                indexing_rate = 1.337,
                indexed_frames = 56,
        )
        """

    def testJsonIndexingFom(self):
        """Test JsonIndexingFom"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
