# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.processing_api import ProcessingApi


class TestProcessingApi(unittest.IsolatedAsyncioTestCase):
    """ProcessingApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ProcessingApi()

    async def asyncTearDown(self) -> None:
        pass

    async def test_indexing_job_finish_successfully_api_indexing_indexing_result_id_success_post(self) -> None:
        """Test case for indexing_job_finish_successfully_api_indexing_indexing_result_id_success_post

        Indexing Job Finish Successfully
        """
        pass

    async def test_indexing_job_finish_with_error_api_indexing_indexing_result_id_finish_with_error_post(self) -> None:
        """Test case for indexing_job_finish_with_error_api_indexing_indexing_result_id_finish_with_error_post

        Indexing Job Finish With Error
        """
        pass

    async def test_indexing_job_get_errorlog_api_indexing_indexing_result_id_errorlog_get(self) -> None:
        """Test case for indexing_job_get_errorlog_api_indexing_indexing_result_id_errorlog_get

        Indexing Job Get Errorlog
        """
        pass

    async def test_indexing_job_get_log_api_indexing_indexing_result_id_log_get(self) -> None:
        """Test case for indexing_job_get_log_api_indexing_indexing_result_id_log_get

        Indexing Job Get Log
        """
        pass

    async def test_indexing_job_queue_for_data_set_api_indexing_post(self) -> None:
        """Test case for indexing_job_queue_for_data_set_api_indexing_post

        Indexing Job Queue For Data Set
        """
        pass

    async def test_indexing_job_still_running_api_indexing_indexing_result_id_still_running_post(self) -> None:
        """Test case for indexing_job_still_running_api_indexing_indexing_result_id_still_running_post

        Indexing Job Still Running
        """
        pass

    async def test_merge_job_get_log_api_merging_merge_result_id_log_get(self) -> None:
        """Test case for merge_job_get_log_api_merging_merge_result_id_log_get

        Merge Job Get Log
        """
        pass

    async def test_read_indexing_jobs_api_indexing_get(self) -> None:
        """Test case for read_indexing_jobs_api_indexing_get

        Read Indexing Jobs
        """
        pass

    async def test_read_indexing_parameters_api_indexing_parameters_data_set_id_get(self) -> None:
        """Test case for read_indexing_parameters_api_indexing_parameters_data_set_id_get

        Read Indexing Parameters
        """
        pass


if __name__ == '__main__':
    unittest.main()
