# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amarcord_open.api.chemicals_api import ChemicalsApi


class TestChemicalsApi(unittest.IsolatedAsyncioTestCase):
    """ChemicalsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ChemicalsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_copy_chemical_api_copy_chemical_post(self) -> None:
        """Test case for copy_chemical_api_copy_chemical_post

        Copy Chemical
        """
        pass

    async def test_create_chemical_api_chemicals_post(self) -> None:
        """Test case for create_chemical_api_chemicals_post

        Create Chemical
        """
        pass

    async def test_delete_chemical_api_chemicals_delete(self) -> None:
        """Test case for delete_chemical_api_chemicals_delete

        Delete Chemical
        """
        pass

    async def test_read_all_chemicals_api_all_chemicals_get(self) -> None:
        """Test case for read_all_chemicals_api_all_chemicals_get

        Read All Chemicals
        """
        pass

    async def test_read_chemicals_api_chemicals_beamtime_id_get(self) -> None:
        """Test case for read_chemicals_api_chemicals_beamtime_id_get

        Read Chemicals
        """
        pass

    async def test_update_chemical_api_chemicals_patch(self) -> None:
        """Test case for update_chemical_api_chemicals_patch

        Update Chemical
        """
        pass


if __name__ == '__main__':
    unittest.main()
