# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amarcord_open.api.beamtimes_api import BeamtimesApi


class TestBeamtimesApi(unittest.IsolatedAsyncioTestCase):
    """BeamtimesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = BeamtimesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_beamtime_api_beamtimes_post(self) -> None:
        """Test case for create_beamtime_api_beamtimes_post

        Create Beamtime
        """
        pass

    async def test_read_beamtime_api_beamtimes_beamtime_id_get(self) -> None:
        """Test case for read_beamtime_api_beamtimes_beamtime_id_get

        Read Beamtime
        """
        pass

    async def test_read_beamtimes_api_beamtimes_get(self) -> None:
        """Test case for read_beamtimes_api_beamtimes_get

        Read Beamtimes
        """
        pass

    async def test_update_beamtime_api_beamtimes_patch(self) -> None:
        """Test case for update_beamtime_api_beamtimes_patch

        Update Beamtime
        """
        pass


if __name__ == '__main__':
    unittest.main()
