# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.json_analysis_run import JsonAnalysisRun

class TestJsonAnalysisRun(unittest.TestCase):
    """JsonAnalysisRun unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JsonAnalysisRun:
        """Test JsonAnalysisRun
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JsonAnalysisRun`
        """
        model = JsonAnalysisRun()
        if include_optional:
            return JsonAnalysisRun(
                id = 56,
                external_id = 56,
                attributi = [
                    openapi_client.models.json_attributo_value.JsonAttributoValue(
                        attributo_id = 56, 
                        attributo_value_str = '', 
                        attributo_value_int = 56, 
                        attributo_value_chemical = 56, 
                        attributo_value_datetime = 56, 
                        attributo_value_float = 1.337, 
                        attributo_value_bool = True, 
                        attributo_value_list_str = [
                            ''
                            ], 
                        attributo_value_list_float = [
                            1.337
                            ], 
                        attributo_value_list_bool = [
                            True
                            ], )
                    ],
                file_paths = [
                    openapi_client.models.json_run_file.JsonRunFile(
                        id = 56, 
                        glob = '', 
                        source = '', )
                    ]
            )
        else:
            return JsonAnalysisRun(
                id = 56,
                external_id = 56,
                attributi = [
                    openapi_client.models.json_attributo_value.JsonAttributoValue(
                        attributo_id = 56, 
                        attributo_value_str = '', 
                        attributo_value_int = 56, 
                        attributo_value_chemical = 56, 
                        attributo_value_datetime = 56, 
                        attributo_value_float = 1.337, 
                        attributo_value_bool = True, 
                        attributo_value_list_str = [
                            ''
                            ], 
                        attributo_value_list_float = [
                            1.337
                            ], 
                        attributo_value_list_bool = [
                            True
                            ], )
                    ],
                file_paths = [
                    openapi_client.models.json_run_file.JsonRunFile(
                        id = 56, 
                        glob = '', 
                        source = '', )
                    ],
        )
        """

    def testJsonAnalysisRun(self):
        """Test JsonAnalysisRun"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
