# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.json_event_top_level_output import JsonEventTopLevelOutput

class TestJsonEventTopLevelOutput(unittest.TestCase):
    """JsonEventTopLevelOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JsonEventTopLevelOutput:
        """Test JsonEventTopLevelOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JsonEventTopLevelOutput`
        """
        model = JsonEventTopLevelOutput()
        if include_optional:
            return JsonEventTopLevelOutput(
                id = 56
            )
        else:
            return JsonEventTopLevelOutput(
                id = 56,
        )
        """

    def testJsonEventTopLevelOutput(self):
        """Test JsonEventTopLevelOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
