# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.schedule_api import ScheduleApi


class TestScheduleApi(unittest.IsolatedAsyncioTestCase):
    """ScheduleApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ScheduleApi()

    async def asyncTearDown(self) -> None:
        pass

    async def test_get_beamtime_schedule_api_schedule_beamtime_id_get(self) -> None:
        """Test case for get_beamtime_schedule_api_schedule_beamtime_id_get

        Get Beamtime Schedule
        """
        pass

    async def test_update_beamtime_schedule_api_schedule_post(self) -> None:
        """Test case for update_beamtime_schedule_api_schedule_post

        Update Beamtime Schedule
        """
        pass


if __name__ == '__main__':
    unittest.main()
