# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from amarcord_open.api.events_api import EventsApi


class TestEventsApi(unittest.IsolatedAsyncioTestCase):
    """EventsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = EventsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_event_api_events_post(self) -> None:
        """Test case for create_event_api_events_post

        Create Event
        """
        pass

    async def test_create_live_stream_snapshot_api_live_stream_snapshot_beamtime_id_get(self) -> None:
        """Test case for create_live_stream_snapshot_api_live_stream_snapshot_beamtime_id_get

        Create Live Stream Snapshot
        """
        pass

    async def test_delete_event_api_events_delete(self) -> None:
        """Test case for delete_event_api_events_delete

        Delete Event
        """
        pass

    async def test_read_events_api_events_beamtime_id_get(self) -> None:
        """Test case for read_events_api_events_beamtime_id_get

        Read Events
        """
        pass


if __name__ == '__main__':
    unittest.main()
