# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.json_update_run_output import JsonUpdateRunOutput

class TestJsonUpdateRunOutput(unittest.TestCase):
    """JsonUpdateRunOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JsonUpdateRunOutput:
        """Test JsonUpdateRunOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JsonUpdateRunOutput`
        """
        model = JsonUpdateRunOutput()
        if include_optional:
            return JsonUpdateRunOutput(
                result = True,
                files = [
                    openapi_client.models.json_run_file.JsonRunFile(
                        id = 56, 
                        glob = '', 
                        source = '', )
                    ]
            )
        else:
            return JsonUpdateRunOutput(
                result = True,
                files = [
                    openapi_client.models.json_run_file.JsonRunFile(
                        id = 56, 
                        glob = '', 
                        source = '', )
                    ],
        )
        """

    def testJsonUpdateRunOutput(self):
        """Test JsonUpdateRunOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
