# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.attributo_type import AttributoType

class TestAttributoType(unittest.TestCase):
    """AttributoType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AttributoType:
        """Test AttributoType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AttributoType`
        """
        model = AttributoType()
        if include_optional:
            return AttributoType(
                type = 'integer',
                format = 'standard-unit',
                minimum = 1.337,
                maximum = 1.337,
                exclusive_minimum = 1.337,
                exclusive_maximum = 1.337,
                suffix = '',
                tolerance = 1.337,
                tolerance_is_absolute = True,
                enum = [
                    ''
                    ],
                item_type = 'string',
                min_items = 56,
                max_items = 56
            )
        else:
            return AttributoType(
                type = 'integer',
                item_type = 'string',
        )
        """

    def testAttributoType(self):
        """Test AttributoType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
