# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List
from openapi_client.models.json_create_attributi_from_schema_single_attributo import JsonCreateAttributiFromSchemaSingleAttributo
from typing import Optional, Set
from typing_extensions import Self

class JsonCreateAttributiFromSchemaInput(BaseModel):
    """
    JsonCreateAttributiFromSchemaInput
    """ # noqa: E501
    attributi_schema: List[JsonCreateAttributiFromSchemaSingleAttributo]
    beamtime_id: StrictInt
    __properties: ClassVar[List[str]] = ["attributi_schema", "beamtime_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JsonCreateAttributiFromSchemaInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attributi_schema (list)
        _items = []
        if self.attributi_schema:
            for _item_attributi_schema in self.attributi_schema:
                if _item_attributi_schema:
                    _items.append(_item_attributi_schema.to_dict())
            _dict['attributi_schema'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JsonCreateAttributiFromSchemaInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attributi_schema": [JsonCreateAttributiFromSchemaSingleAttributo.from_dict(_item) for _item in obj["attributi_schema"]] if obj.get("attributi_schema") is not None else None,
            "beamtime_id": obj.get("beamtime_id")
        })
        return _obj


