# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List
from openapi_client.models.json_attributo import JsonAttributo
from openapi_client.models.json_attributo_bulk_value import JsonAttributoBulkValue
from openapi_client.models.json_chemical import JsonChemical
from openapi_client.models.json_experiment_type import JsonExperimentType
from typing import Optional, Set
from typing_extensions import Self

class JsonReadRunsBulkOutput(BaseModel):
    """
    JsonReadRunsBulkOutput
    """ # noqa: E501
    chemicals: List[JsonChemical]
    attributi: List[JsonAttributo]
    attributi_values: List[JsonAttributoBulkValue]
    experiment_types: List[JsonExperimentType]
    experiment_type_ids: List[StrictInt]
    __properties: ClassVar[List[str]] = ["chemicals", "attributi", "attributi_values", "experiment_types", "experiment_type_ids"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JsonReadRunsBulkOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in chemicals (list)
        _items = []
        if self.chemicals:
            for _item_chemicals in self.chemicals:
                if _item_chemicals:
                    _items.append(_item_chemicals.to_dict())
            _dict['chemicals'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in attributi (list)
        _items = []
        if self.attributi:
            for _item_attributi in self.attributi:
                if _item_attributi:
                    _items.append(_item_attributi.to_dict())
            _dict['attributi'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in attributi_values (list)
        _items = []
        if self.attributi_values:
            for _item_attributi_values in self.attributi_values:
                if _item_attributi_values:
                    _items.append(_item_attributi_values.to_dict())
            _dict['attributi_values'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in experiment_types (list)
        _items = []
        if self.experiment_types:
            for _item_experiment_types in self.experiment_types:
                if _item_experiment_types:
                    _items.append(_item_experiment_types.to_dict())
            _dict['experiment_types'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JsonReadRunsBulkOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "chemicals": [JsonChemical.from_dict(_item) for _item in obj["chemicals"]] if obj.get("chemicals") is not None else None,
            "attributi": [JsonAttributo.from_dict(_item) for _item in obj["attributi"]] if obj.get("attributi") is not None else None,
            "attributi_values": [JsonAttributoBulkValue.from_dict(_item) for _item in obj["attributi_values"]] if obj.get("attributi_values") is not None else None,
            "experiment_types": [JsonExperimentType.from_dict(_item) for _item in obj["experiment_types"]] if obj.get("experiment_types") is not None else None,
            "experiment_type_ids": obj.get("experiment_type_ids")
        })
        return _obj


