# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class JSONSchemaNumber(BaseModel):
    """
    JSONSchemaNumber
    """ # noqa: E501
    type: StrictStr
    minimum: Optional[Union[StrictFloat, StrictInt]] = None
    maximum: Optional[Union[StrictFloat, StrictInt]] = None
    exclusive_minimum: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="exclusiveMinimum")
    exclusive_maximum: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="exclusiveMaximum")
    suffix: Optional[StrictStr] = None
    format: Optional[StrictStr] = None
    tolerance: Optional[Union[StrictFloat, StrictInt]] = None
    tolerance_is_absolute: Optional[StrictBool] = Field(default=False, alias="toleranceIsAbsolute")
    __properties: ClassVar[List[str]] = ["type", "minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum", "suffix", "format", "tolerance", "toleranceIsAbsolute"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['number']):
            raise ValueError("must be one of enum values ('number')")
        return value

    @field_validator('format')
    def format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['standard-unit']):
            raise ValueError("must be one of enum values ('standard-unit')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JSONSchemaNumber from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JSONSchemaNumber from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "minimum": obj.get("minimum"),
            "maximum": obj.get("maximum"),
            "exclusiveMinimum": obj.get("exclusiveMinimum"),
            "exclusiveMaximum": obj.get("exclusiveMaximum"),
            "suffix": obj.get("suffix"),
            "format": obj.get("format"),
            "tolerance": obj.get("tolerance"),
            "toleranceIsAbsolute": obj.get("toleranceIsAbsolute") if obj.get("toleranceIsAbsolute") is not None else False
        })
        return _obj


