# coding: utf-8

"""
    AMARCORD OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MergeNegativeHandling(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    IGNORE = 'ignore'
    ZERO = 'zero'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MergeNegativeHandling from a JSON string"""
        return cls(json.loads(json_str))


